[theme]
base = "light"
primaryColor = "#D50032"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#10233F"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true

